using UnityEngine;

public class Door : MonoBehaviour
{
    [SerializeField] private Transform previuosRoom;
    [SerializeField] private Transform nextRoom;
    [SerializeField] private CameraController cam;

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.tag == "Player")
        {
            if (collision.transform.position.x < transform.position.x)
            {
                cam.MoveToNewRoom(nextRoom);
                nextRoom.GetComponent<Room>().ActivateRoom(true);
                previuosRoom.GetComponent<Room>().ActivateRoom(false);
            }

            else
            {
                cam.MoveToNewRoom(previuosRoom);
                previuosRoom.GetComponent<Room>().ActivateRoom(true);
                nextRoom.GetComponent<Room>().ActivateRoom(false);

            }
        }
    }
}
